<?php
declare(strict_types=1);
require __DIR__.'/config/bootstrap.php';
$context=requireModuleAccess('catalogos');$user=$context['user'];$module=$context['module'];$menu=modulesForRole((string)$user['role']);$activeModule='catalogos';$pageTitle='Catálogos';
$catalogs=require __DIR__.'/config/demo_catalogs.php';$catalogs=is_array($catalogs)?$catalogs:[];$canManageCatalogs=(string)$user['role']==='gerente';$json=json_encode($catalogs,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT);if($json===false)$json='{}';
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= e(APP_NAME) ?> | <?= e($pageTitle) ?></title><link rel="stylesheet" href="assets/css/app.css?v=BS-20260627-203011-COT"><link rel="stylesheet" href="assets/css/modules.css?v=BS-20260627-203011-COT"><link rel="stylesheet" href="assets/css/catalogos.css?v=BS-20260627-203011-COT"><link rel="stylesheet" href="assets/css/catalogos-logos.css?v=BS-20260627-203011-COT"><link rel="stylesheet" href="assets/css/notifications.css?v=BS-20260627-203011-COT"></head>
<body class="app-body" data-role="<?= e((string)$user['role']) ?>" data-user="<?= e((string)$user['id']) ?>" data-catalog-manager="<?= $canManageCatalogs?'1':'0' ?>"><div class="app-shell"><?php require __DIR__.'/views/partials/sidebar.php';?><div class="sidebar-overlay" id="sidebar-overlay"></div><main class="workspace"><?php require __DIR__.'/views/partials/topbar.php';?><section class="workspace-content"><article class="module-hero catalogs-hero"><div class="module-hero-icon" aria-hidden="true"><?= e((string)($module['icon']??'▤')) ?></div><div><p class="eyebrow">CONFIGURACIÓN OPERATIVA</p><h2>Catálogos demo</h2><p>Valida los datos maestros de cotizaciones, pólizas y otros módulos antes de definir tablas MySQL.</p></div><span class="module-access-badge"><?= $canManageCatalogs?'Edición demo habilitada':'Consulta habilitada' ?></span></article>
<section class="catalogs-layout" id="catalogs-app"><aside class="catalog-groups-panel"><div class="catalog-groups-heading"><div><p class="eyebrow">GRUPOS DISPONIBLES</p><h2>Datos maestros</h2></div><span id="catalog-count" class="catalog-count">0</span></div><div id="catalog-groups" class="catalog-groups" role="tablist"></div></aside><section class="catalog-content-panel"><div class="catalog-content-heading"><div><p id="catalog-current-eyebrow" class="eyebrow">CATÁLOGO</p><h2 id="catalog-current-title">Cargando catálogo</h2><p id="catalog-current-description">Cargando información demo.</p></div><div class="catalog-actions"><?php if($canManageCatalogs):?><button id="restore-catalogs" class="catalog-secondary-button" type="button">Restaurar demo</button><button id="add-catalog-item" class="catalog-primary-button" type="button">+ Agregar elemento</button><?php endif;?></div></div><?php if($canManageCatalogs):?><div class="catalog-notice catalog-notice-manager"><strong>Modo gerente:</strong> puedes agregar, editar, activar o desactivar elementos. En Aseguradoras también puedes cargar un logo opcional.</div><?php else:?><div class="catalog-notice"><strong>Modo consulta:</strong> puedes revisar los catálogos disponibles, pero no modificar elementos.</div><?php endif;?><div class="catalog-table-wrap"><table class="catalog-table"><thead><tr><th>Código</th><th>Nombre</th><th>Detalle</th><th>Estado</th><?php if($canManageCatalogs):?><th class="catalog-actions-column">Acciones</th><?php endif;?></tr></thead><tbody id="catalog-table-body"><tr><td colspan="<?= $canManageCatalogs?'5':'4' ?>">Cargando elementos…</td></tr></tbody></table></div><p id="catalog-empty" class="catalog-empty" hidden>No hay elementos registrados en este catálogo.</p></section></section></section></main></div>
<?php if($canManageCatalogs):?><dialog id="catalog-item-dialog" class="catalog-dialog"><form id="catalog-item-form" method="dialog"><div class="catalog-dialog-heading"><div><p class="eyebrow">EDICIÓN TEMPORAL</p><h2 id="catalog-dialog-title">Agregar elemento</h2></div><button id="catalog-dialog-close" class="catalog-dialog-close" type="button">×</button></div><input id="catalog-item-id" type="hidden"><label for="catalog-item-code">Código</label><input id="catalog-item-code" maxlength="20" required><label for="catalog-item-name">Nombre</label><input id="catalog-item-name" maxlength="100" required><label for="catalog-item-detail">Detalle</label><textarea id="catalog-item-detail" rows="3" maxlength="180"></textarea><label for="catalog-item-status">Estado</label><select id="catalog-item-status"><option value="Activo">Activo</option><option value="Inactivo">Inactivo</option></select><div class="catalog-dialog-actions"><button id="catalog-dialog-cancel" class="catalog-secondary-button" type="button">Cancelar</button><button class="catalog-primary-button" type="submit">Guardar cambio demo</button></div></form></dialog><?php endif;?>
<script id="catalog-default-data" type="application/json"><?= $json ?></script><script src="assets/js/cache-migrations.js?v=BS-20260627-203011-COT"></script><script src="assets/js/app.js?v=BS-20260627-203011-COT"></script><script src="assets/js/catalogos.js?v=BS-20260627-203011-COT"></script><script src="assets/js/catalogos-logos.js?v=BS-20260627-203011-COT"></script></body></html>
