<?php
declare(strict_types=1);
require __DIR__ . '/config/bootstrap.php';
$context=requireModuleAccess('clientes');
$user=$context['user']; $module=$context['module']; $menu=modulesForRole((string)$user['role']); $activeModule='clientes'; $pageTitle='Clientes';
$data=require __DIR__.'/config/demo_clients.php';
$json=json_encode(is_array($data)?$data:[],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?:'{}';
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e(APP_NAME) ?> | <?= e($pageTitle) ?></title><link rel="stylesheet" href="assets/css/app.css"><link rel="stylesheet" href="assets/css/modules.css"><link rel="stylesheet" href="assets/css/clientes.css"></head>
<body class="app-body" data-role="<?= e((string)$user['role']) ?>"><div class="app-shell"><?php require __DIR__.'/views/partials/sidebar.php'; ?><div class="sidebar-overlay" id="sidebar-overlay"></div><main class="workspace"><?php require __DIR__.'/views/partials/topbar.php'; ?><section class="workspace-content">
<article class="module-hero"><div class="module-hero-icon">♙</div><div><p class="eyebrow">GESTIÓN OPERATIVA</p><h2>Clientes y entidades</h2><p>Administra empresas, consorcios y contactos de gestión. Los registros se pueden completar progresivamente.</p></div><span class="module-access-badge">Gerente y ejecutivo</span></article>
<section id="clients-app" class="clients-app"><div class="clients-summary-grid"><article class="client-summary-card"><span>▦</span><p>Empresas activas</p><strong id="summary-companies">0</strong><small>Disponibles para nuevas vinculaciones</small></article><article class="client-summary-card primary"><span>▧</span><p>Consorcios activos</p><strong id="summary-consortia">0</strong><small>Con RUC propio u operador</small></article><article class="client-summary-card success"><span>♙</span><p>Contactos activos</p><strong id="summary-contacts">0</strong><small>Personas naturales de gestión</small></article><article class="client-summary-card warning"><span>◌</span><p>Entidades inactivas</p><strong id="summary-inactive">0</strong><small>Conservadas como antecedente</small></article></div>
<section class="clients-panel"><div class="clients-panel-heading"><div><p class="eyebrow">CARTERA Y CONTACTOS</p><h2 id="section-title">Empresas</h2><p id="section-help">Registra empresas con razón social o RUC. Si registras RUC, debe ser válido y único.</p></div><button id="add-record" class="client-primary" type="button">+ Nueva empresa</button></div>
<div class="clients-tabs"><button class="client-tab active" type="button" data-tab="companies">Empresas</button><button class="client-tab" type="button" data-tab="consortia">Consorcios</button><button class="client-tab" type="button" data-tab="contacts">Contactos de gestión</button></div>
<div class="clients-filters"><label><span>Buscar</span><input id="search" type="search" placeholder="Nombre, RUC, correo, celular"></label><label><span>Estado</span><select id="status"><option value="active">Activos</option><option value="inactive">Inactivos</option><option value="all">Todos</option></select></label><button id="clear-filters" class="client-secondary" type="button">Limpiar filtros</button></div>
<div class="table-wrap"><table class="clients-table"><thead id="table-head"></thead><tbody id="table-body"><tr><td>Cargando registros…</td></tr></tbody></table></div><p id="empty" class="empty" hidden>No existen registros para los filtros seleccionados.</p></section></section>
</section></main></div>
<dialog id="form-dialog" class="client-dialog"><form id="record-form" method="dialog" novalidate><div class="dialog-head"><div><p class="eyebrow" id="form-eyebrow">CLIENTES</p><h2 id="form-title">Registro</h2></div><button id="close-form" class="close" type="button" aria-label="Cerrar">×</button></div><div id="form-content"></div><div class="dialog-actions"><button id="cancel-form" class="client-secondary" type="button">Cancelar</button><button class="client-primary" type="submit">Guardar</button></div></form></dialog>
<dialog id="deactivate-dialog" class="client-dialog danger-dialog"><form id="deactivate-form" method="dialog" novalidate><div class="dialog-head"><div><p class="eyebrow">ACCIÓN DE DESACTIVACIÓN</p><h2>Desactivar y conservar historial</h2></div><button id="close-deactivate" class="close" type="button" aria-label="Cerrar">×</button></div><p id="deactivate-message" class="danger-message"></p><label class="field"><span>Motivo <b>*</b></span><textarea id="deactivate-reason" rows="4" maxlength="400" required placeholder="Indica por qué se desactiva."></textarea></label><div class="dialog-actions"><button id="cancel-deactivate" class="client-secondary" type="button">Cancelar</button><button class="client-danger" type="submit">Desactivar</button></div></form></dialog>
<script id="client-data" type="application/json"><?= $json ?></script><script src="assets/js/cache-migrations.js"></script><script src="assets/js/app.js"></script><script src="assets/js/clientes.js"></script></body></html>
