<?php
declare(strict_types=1);
require __DIR__ . '/config/bootstrap.php';
$context=requireModuleAccess('cotizaciones'); $user=$context['user']; $module=$context['module']; $menu=modulesForRole((string)$user['role']); $activeModule='cotizaciones'; $pageTitle='Cotizaciones';
$catalogs=require __DIR__.'/config/demo_catalogs.php'; $expedients=require __DIR__.'/config/demo_expedients.php'; $clients=require __DIR__.'/config/demo_clients.php'; $templates=require __DIR__.'/config/demo_quote_templates.php';
function qjson(mixed $value): string { $json=json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT); return $json===false?'{}':$json; }
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= e(APP_NAME) ?> | <?= e($pageTitle) ?></title>
<link rel="stylesheet" href="assets/css/app.css?v=BS-20260627-213052-HUBV2"><link rel="stylesheet" href="assets/css/modules.css?v=BS-20260627-213052-HUBV2"><link rel="stylesheet" href="assets/css/modal-ui.css?v=BS-20260627-213052-HUBV2"><link rel="stylesheet" href="assets/css/notifications.css?v=BS-20260627-213052-HUBV2"><link rel="stylesheet" href="assets/css/cotizaciones.css?v=BS-20260627-213052-HUBV2">    <link rel="stylesheet" href="assets/css/cotizaciones-v2-enhancements.css?v=BS-20260627-213052-HUBV2">
</head>
<body class="app-body" data-role="<?= e((string)$user['role']) ?>" data-user="<?= e((string)$user['id']) ?>"><div class="app-shell"><?php require __DIR__.'/views/partials/sidebar.php'; ?><div class="sidebar-overlay" id="sidebar-overlay"></div><main class="workspace"><?php require __DIR__.'/views/partials/topbar.php'; ?><section class="workspace-content">
<article class="module-hero quotes-hero"><div class="module-hero-icon" aria-hidden="true"><?= e((string)($module['icon']??'▤')) ?></div><div><p class="eyebrow">NÚCLEO COMERCIAL</p><h2>Cotizaciones demo</h2><p>Toda cotización pertenece obligatoriamente a un expediente. Es un antecedente comercial independiente: no crea, modifica ni se vincula con pólizas o seguros emitidos.</p></div><span class="module-access-badge">Plantillas y vista A4</span></article>
<section id="quotes-app" class="quotes-app">
<section id="quotes-home"><div class="quotes-summary-grid"><article class="quote-summary-card"><span>▤</span><p>Cotizaciones</p><strong id="quote-total">0</strong><small>En este navegador</small></article><article class="quote-summary-card quote-summary-primary"><span>✓</span><p>Aceptadas</p><strong id="quote-accepted">0</strong><small>Con decisión explícita</small></article><article class="quote-summary-card quote-summary-warning"><span>◷</span><p>Vencidas visualmente</p><strong id="quote-expired">0</strong><small>Vigencia opcional</small></article></div>
<div class="quotes-toolbar"><div><p class="eyebrow">DOCUMENTOS COMERCIALES</p><h2>Plantillas y cotizaciones</h2><p>Cada cotización tiene un expediente padre obligatorio. Su información comercial es independiente de las pólizas y seguros reales del expediente.</p></div><div class="quotes-toolbar-actions"><button id="quote-new-template" class="quote-secondary-button" type="button">+ Plantilla</button><button id="quote-new" class="quote-primary-button" type="button">+ Nueva cotización</button></div></div>
<div class="quotes-home-grid"><section class="quotes-panel"><div class="quotes-panel-heading"><div><p class="eyebrow">PLANTILLAS</p><h3>Base de documento</h3></div><span id="template-count" class="quote-count-badge">0</span></div><div id="quote-template-list" class="quote-template-list"></div></section><section class="quotes-panel"><div class="quotes-panel-heading"><div><p class="eyebrow">COTIZACIONES</p><h3>Documentos registrados</h3></div><label class="quote-search"><span>Buscar</span><input id="quote-search" type="search" placeholder="Código, título, cliente o expediente"></label></div><div id="quote-list" class="quote-list"></div><p id="quote-empty" class="quote-empty" hidden>No hay cotizaciones que coincidan con la búsqueda.</p></section></div></section>
<section id="quote-editor-view" hidden></section><section id="quote-preview-view" hidden></section></section></section></main></div>
<dialog id="quote-template-dialog" class="quote-dialog"><form id="quote-template-form" method="dialog"><div class="quote-dialog-heading"><div><p class="eyebrow">PLANTILLA</p><h2 id="quote-template-dialog-title">Nueva plantilla</h2></div><button id="quote-template-close" class="quote-dialog-close" type="button" aria-label="Cerrar">×</button></div><input id="t-id" type="hidden"><div class="quote-form-grid"><label class="quote-field-wide"><span>Nombre <b>*</b></span><input id="t-name" maxlength="100" required></label><label class="quote-field-wide"><span>Descripción</span><textarea id="t-description" rows="2" maxlength="250"></textarea></label><label><span>Símbolo</span><input id="t-symbol" maxlength="4" value="BS"></label><label><span>Nombre del corredor <b>*</b></span><input id="t-broker" maxlength="100" value="BROKER SEGUROS" required></label><label class="quote-field-wide"><span>Título <b>*</b></span><input id="t-title" maxlength="120" value="COTIZACIÓN DE SEGURO" required></label><label class="quote-field-wide"><span>Subtítulo</span><input id="t-subtitle" maxlength="150"></label><label><span>Teléfono</span><input id="t-phone" maxlength="60"></label><label><span>Correo</span><input id="t-email" type="email" maxlength="100"></label><label class="quote-field-wide"><span>Pie</span><textarea id="t-footer" rows="3" maxlength="600"></textarea></label><label><span>Grupo inicial</span><input id="t-group" maxlength="80" value="Alternativas"></label><label><span>Datos sugeridos</span><textarea id="t-data" rows="4" maxlength="600" placeholder="Un dato por línea"></textarea></label><label class="quote-field-wide"><span>Adicionales sugeridos</span><textarea id="t-additional" rows="3" maxlength="600" placeholder="Un título por línea"></textarea></label></div><div class="quote-dialog-actions"><button id="quote-template-cancel" class="quote-secondary-button" type="button">Cancelar</button><button class="quote-primary-button" type="submit">Guardar plantilla</button></div></form></dialog>
<script id="quote-default-templates" type="application/json"><?= qjson($templates) ?></script><script id="quote-default-catalogs" type="application/json"><?= qjson($catalogs) ?></script><script id="quote-default-expedients" type="application/json"><?= qjson($expedients) ?></script><script id="quote-default-clients" type="application/json"><?= qjson($clients) ?></script>
<script src="assets/js/cache-migrations.js?v=BS-20260627-213052-HUBV2"></script><script src="assets/js/activity-timeline.js?v=BS-20260627-213052-HUBV2"></script><script src="assets/js/app.js?v=BS-20260627-213052-HUBV2"></script><script src="assets/js/cotizaciones.js?v=BS-20260627-213052-HUBV2"></script>    <script src="assets/js/cotizaciones-v2-enhancements.js?v=BS-20260627-213052-HUBV2"></script>
</body></html>
