<?php
declare(strict_types=1);
require __DIR__ . '/config/bootstrap.php';
$context=requireModuleAccess('mis-pagos');$user=$context['user'];$module=$context['module'];$menu=modulesForRole((string)$user['role']);$activeModule='mis-pagos';$pageTitle='Mis Pagos';
if((string)$user['role']!=='cliente'){header('Location: '.appRelativeUrl('acceso_denegado.php?modulo=mis-pagos&motivo=permiso'));exit;}
$expedients=require __DIR__.'/config/demo_expedients.php';$clients=require __DIR__.'/config/demo_clients.php';
function pjson(mixed $v):string{$j=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT);return $j===false?'{}':$j;}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?=e(APP_NAME)?> | <?=e($pageTitle)?></title><link rel="stylesheet" href="assets/css/app.css?v=BS-20260627-222604-PAYCLIENTV1"><link rel="stylesheet" href="assets/css/modules.css?v=BS-20260627-222604-PAYCLIENTV1"><link rel="stylesheet" href="assets/css/client-payments.css?v=BS-20260627-222604-PAYCLIENTV1"></head>
<body class="app-body" data-role="<?=e((string)$user['role'])?>" data-user="<?=e((string)$user['id'])?>" data-client-name="<?=e((string)$user['name'])?>" data-client-entity="<?=e((string)($user['entity_name']??$user['name']))?>" data-client-document="<?=e((string)$user['document'])?>"><div class="app-shell"><?php require __DIR__.'/views/partials/sidebar.php';?><div class="sidebar-overlay" id="sidebar-overlay"></div><main class="workspace"><?php require __DIR__.'/views/partials/topbar.php';?><section class="workspace-content">
<article class="module-hero"><div class="module-hero-icon" aria-hidden="true">◉</div><div><p class="eyebrow">PORTAL DE CLIENTE</p><h2>Mis pagos</h2><p>Revisa el cronograma de tus pólizas y envía comprobantes para validación.</p></div><span class="module-access-badge">Solo consulta y comprobantes</span></article>
<section id="client-payments-app" class="client-payments-app"><div class="client-payments-summary"><article><p>Pendientes</p><strong id="payments-pending-total">0</strong><small>Cuotas por gestionar</small></article><article class="is-warning"><p>Vencidos</p><strong id="payments-overdue-total">0</strong><small>Con fecha superada</small></article><article class="is-primary"><p>Comprobantes enviados</p><strong id="payments-review-total">0</strong><small>Esperando validación</small></article></div>
<div class="client-payments-toolbar"><div><p class="eyebrow">CRONOGRAMA DE PAGOS</p><h3>Mis cuotas</h3><p>El comprobante se envía a revisión. La corredora confirmará el pago cuando sea validado.</p></div><label><span>Ver</span><select id="client-payment-filter"><option value="all">Todas</option><option value="pending">Pendientes</option><option value="overdue">Vencidas</option><option value="review">En revisión</option><option value="paid">Pagadas</option></select></label></div><div id="client-payment-list" class="client-payment-list"></div><p id="client-payment-empty" class="client-payment-empty" hidden>No hay cuotas de pago disponibles para esta cuenta.</p><div class="client-payments-info"><strong>Importante:</strong><span>Sube PDF, PNG, JPG o WEBP de hasta 7 MB. El archivo queda pendiente de revisión y no confirma el pago por sí solo.</span></div></section>
</section></main></div>
<dialog id="client-receipt-dialog" class="client-receipt-dialog"><form id="client-receipt-form" class="client-receipt-content"><div class="client-receipt-heading"><div><p class="eyebrow">COMPROBANTE DE PAGO</p><h2 id="client-receipt-title">Enviar comprobante</h2></div><button id="client-receipt-close" class="client-receipt-close" type="button" aria-label="Cerrar">×</button></div><input id="client-receipt-policy-id" type="hidden"><input id="client-receipt-payment-id" type="hidden"><p id="client-receipt-description" class="client-receipt-description"></p><label class="client-receipt-file"><span>Archivo <b>*</b></span><input id="client-receipt-file" type="file" accept="application/pdf,image/png,image/jpeg,image/webp,.pdf,.png,.jpg,.jpeg,.webp" required><small>PDF, PNG, JPG o WEBP · máximo 7 MB.</small></label><label class="client-receipt-file"><span>Nota para la corredora</span><textarea id="client-receipt-note" rows="3" maxlength="500"></textarea></label><div id="client-receipt-progress" class="client-receipt-progress" hidden><progress max="100" value="0"></progress><span>Subiendo comprobante…</span></div><div class="client-receipt-actions"><button id="client-receipt-cancel" class="client-secondary-button" type="button">Cancelar</button><button id="client-receipt-submit" class="client-primary-button" type="submit">Enviar a revisión</button></div></form></dialog>
<script id="payment-default-expedients" type="application/json"><?=pjson($expedients)?></script><script id="payment-default-clients" type="application/json"><?=pjson($clients)?></script><script src="assets/js/cache-migrations.js?v=BS-20260627-222604-PAYCLIENTV1"></script><script src="assets/js/app.js?v=BS-20260627-222604-PAYCLIENTV1"></script><script src="assets/js/client-payments.js?v=BS-20260627-222604-PAYCLIENTV1"></script></body></html>
