<?php
declare(strict_types=1);

/**
 * Datos demo del módulo Expedientes.
 *
 * Este archivo representa el núcleo operativo temporal antes de MySQL.
 * La información puede modificarse en la maqueta, pero los cambios del
 * navegador se guardan solo en localStorage.
 */
return [
    'clients' => [
        [
            'id' => 'cli-001',
            'name' => 'Constructora Norte S.A.C.',
            'document_type' => 'RUC',
            'document' => '20123456789',
            'entity_type' => 'Empresa',
        ],
        [
            'id' => 'cli-002',
            'name' => 'Ingeniería Andina S.A.C.',
            'document_type' => 'RUC',
            'document' => '20456789123',
            'entity_type' => 'Empresa',
        ],
        [
            'id' => 'cli-003',
            'name' => 'Consorcio Vías del Norte',
            'document_type' => 'RUC',
            'document' => '20698765432',
            'entity_type' => 'Consorcio',
        ],
        [
            'id' => 'cli-004',
            'name' => 'Transportes El Sol S.A.C.',
            'document_type' => 'RUC',
            'document' => '20511843721',
            'entity_type' => 'Empresa',
        ],
        [
            'id' => 'cli-005',
            'name' => 'Comercial Valle Norte E.I.R.L.',
            'document_type' => 'RUC',
            'document' => '20601856342',
            'entity_type' => 'Empresa',
        ],
    ],
    'executives' => [
        [
            'user_id' => '2',
            'name' => 'María Torres',
            'label' => 'Ejecutiva de seguros',
            'active' => true,
        ],
        [
            'user_id' => 'exec-003',
            'name' => 'Jorge Ramírez',
            'label' => 'Ejecutivo de seguros',
            'active' => true,
        ],
        [
            'user_id' => 'exec-004',
            'name' => 'Ana Pérez',
            'label' => 'Ejecutiva de seguros',
            'active' => true,
        ],
    ],
    'management_types' => [
        'Cotización',
        'Emisión',
        'Renovación',
        'Endoso',
        'Consulta',
        'Regularización',
    ],
    'items' => [
        [
            'id' => 'exp-demo-001',
            'code' => 'EXP-2026-0001',
            'client_id' => 'cli-001',
            'client_name' => 'Constructora Norte S.A.C.',
            'client_document' => 'RUC 20123456789',
            'entity_type' => 'Empresa',
            'management_type' => 'Renovación',
            'insurance_type' => 'Todo Riesgo Construcción',
            'insurer' => 'Pacífico Seguros',
            'currency' => 'PEN',
            'state' => 'En gestión',
            'responsible_user_id' => '2',
            'responsible_name' => 'María Torres',
            'opened_at' => '2026-06-23',
            'updated_at' => '2026-06-27 09:30:00',
            'description' => 'Renovación de cobertura CAR para obra vial. Pendiente de confirmar condiciones comerciales.',
        ],
        [
            'id' => 'exp-demo-002',
            'code' => 'EXP-2026-0002',
            'client_id' => 'cli-002',
            'client_name' => 'Ingeniería Andina S.A.C.',
            'client_document' => 'RUC 20456789123',
            'entity_type' => 'Empresa',
            'management_type' => 'Cotización',
            'insurance_type' => 'Equipo Contratista',
            'insurer' => 'Mapfre Perú',
            'currency' => 'USD',
            'state' => 'Pendiente de documentos',
            'responsible_user_id' => '2',
            'responsible_name' => 'María Torres',
            'opened_at' => '2026-06-25',
            'updated_at' => '2026-06-27 10:15:00',
            'description' => 'Cotización de equipo contratista. Falta relación valorizada de equipos y ubicación de la obra.',
        ],
        [
            'id' => 'exp-demo-003',
            'code' => 'EXP-2026-0003',
            'client_id' => 'cli-003',
            'client_name' => 'Consorcio Vías del Norte',
            'client_document' => 'RUC 20698765432',
            'entity_type' => 'Consorcio',
            'management_type' => 'Emisión',
            'insurance_type' => 'SCTR Salud y Pensión',
            'insurer' => 'La Positiva',
            'currency' => 'PEN',
            'state' => 'En gestión',
            'responsible_user_id' => 'exec-003',
            'responsible_name' => 'Jorge Ramírez',
            'opened_at' => '2026-06-20',
            'updated_at' => '2026-06-26 16:40:00',
            'description' => 'Emisión de cobertura SCTR para personal declarado por el consorcio.',
        ],
        [
            'id' => 'exp-demo-004',
            'code' => 'EXP-2026-0004',
            'client_id' => 'cli-004',
            'client_name' => 'Transportes El Sol S.A.C.',
            'client_document' => 'RUC 20511843721',
            'entity_type' => 'Empresa',
            'management_type' => 'Endoso',
            'insurance_type' => 'Responsabilidad Civil',
            'insurer' => 'Rímac Seguros',
            'currency' => 'PEN',
            'state' => 'Borrador',
            'responsible_user_id' => 'exec-004',
            'responsible_name' => 'Ana Pérez',
            'opened_at' => '2026-06-27',
            'updated_at' => '2026-06-27 08:20:00',
            'description' => 'Solicitud de endoso para actualización de unidad vehicular declarada.',
        ],
        [
            'id' => 'exp-demo-005',
            'code' => 'EXP-2026-0005',
            'client_id' => 'cli-005',
            'client_name' => 'Comercial Valle Norte E.I.R.L.',
            'client_document' => 'RUC 20601856342',
            'entity_type' => 'Empresa',
            'management_type' => 'Regularización',
            'insurance_type' => 'Vida Ley',
            'insurer' => 'Interseguro',
            'currency' => 'PEN',
            'state' => 'Cerrado',
            'responsible_user_id' => '2',
            'responsible_name' => 'María Torres',
            'opened_at' => '2026-06-11',
            'updated_at' => '2026-06-24 14:05:00',
            'description' => 'Regularización de datos de asegurados. Gestión concluida con confirmación del cliente.',
        ],
    ],
];
