<?php
declare(strict_types=1);

/**
 * Usuarios de demostración para la maqueta.
 * No usar estas credenciales ni esta estructura en producción.
 */
return [
    [
        'id' => 1,
        'document_type' => 'DNI',
        'document' => '12345678',
        'password_hash' => '$2y$12$ADcxwbVWd6cWRSq0PZLkEeVVt1SfozmLLryd/oDIpyEWDPhC38Rai',
        'role' => 'gerente',
        'role_label' => 'Gerente',
        'account_type' => 'persona',
        'name' => 'Helmut Leiva',
        'profile_title' => 'Gerente corredor de seguros',
        'entity_name' => 'LIVP Seguros',
        'entity_type' => 'Corredora de seguros',
        'scope' => 'Acceso global al sistema',
        'contact_email' => 'helmut@livpseguros.demo',
        'contact_phone' => '949 579 577',
    ],
    [
        'id' => 2,
        'document_type' => 'DNI',
        'document' => '87654321',
        'password_hash' => '$2y$12$l/xDkgXzEFl.IS9MZWPTkuqlB0kPKo9xb.1E60YiZi8rHgQadUBmi',
        'role' => 'ejecutivo',
        'role_label' => 'Ejecutivo',
        'account_type' => 'persona',
        'name' => 'María Torres',
        'profile_title' => 'Ejecutiva de seguros',
        'entity_name' => 'LIVP Seguros',
        'entity_type' => 'Equipo comercial',
        'scope' => 'Acceso operativo a expedientes',
        'contact_email' => 'maria.torres@livpseguros.demo',
        'contact_phone' => '949 579 578',
    ],
    [
        'id' => 3,
        'document_type' => 'RUC',
        'document' => '20123456789',
        'password_hash' => '$2y$12$uQae/cK.jZZzax/pPAsfZuKKoLu7gb7CqVlhEYO8nyGtIzcrwa8JG',
        'role' => 'cliente',
        'role_label' => 'Cliente',
        'account_type' => 'empresa',
        'name' => 'Constructora Norte S.A.C.',
        'profile_title' => 'Empresa cliente',
        'entity_name' => 'Constructora Norte S.A.C.',
        'entity_type' => 'Empresa',
        'scope' => 'Consulta de seguros, pagos y siniestros',
        'contact_email' => 'contacto@constructoranorte.demo',
        'contact_phone' => '949 579 579',
    ],
    [
        'id' => 4,
        'document_type' => 'RUC',
        'document' => '20698765432',
        'password_hash' => '$2y$12$foh2bCkO66w2sa.81ZQZGebO5lStdbMJcam.H2sJV5WzhjXkGpP5.',
        'role' => 'cliente',
        'role_label' => 'Cliente',
        'account_type' => 'consorcio',
        'name' => 'Consorcio Vías del Norte',
        'profile_title' => 'Consorcio cliente',
        'entity_name' => 'Consorcio Vías del Norte',
        'entity_type' => 'Consorcio con RUC propio',
        'scope' => 'Consulta de seguros, pagos y siniestros',
        'contact_email' => 'contacto@consorcioviasnorte.demo',
        'contact_phone' => '949 579 580',
        'consortium_members' => [
            'Constructora Norte S.A.C. — RUC 20123456789',
            'Ingeniería Andina S.A.C. — RUC 20456789123',
        ],
    ],
];
