<?php
declare(strict_types=1);

return [
    'companies' => [
        ['id'=>'company-001','name'=>'Constructora Norte S.A.C.','ruc'=>'20512345671','phone'=>'044 610 101','email'=>'contacto@constructoranorte.demo','address'=>'Av. Industrial 120, Trujillo','observations'=>'Empresa demo activa.','active'=>true,'created_at'=>'2026-06-20 09:00:00','updated_at'=>'2026-06-20 09:00:00'],
        ['id'=>'company-002','name'=>'Ingeniería Andina S.A.C.','ruc'=>'20456789120','phone'=>'044 610 102','email'=>'administracion@ingenieriaandina.demo','address'=>'Calle Los Álamos 250, Trujillo','observations'=>'','active'=>true,'created_at'=>'2026-06-20 09:10:00','updated_at'=>'2026-06-20 09:10:00'],
        ['id'=>'company-003','name'=>'Transportes El Sol S.A.C.','ruc'=>'20511843724','phone'=>'044 610 103','email'=>'operaciones@transporteselsol.demo','address'=>'Carretera Industrial km 4, Trujillo','observations'=>'Operador tributario de un consorcio demo.','active'=>true,'created_at'=>'2026-06-20 09:20:00','updated_at'=>'2026-06-20 09:20:00'],
        ['id'=>'company-004','name'=>'Comercial Valle Norte E.I.R.L.','ruc'=>'20601856345','phone'=>'044 610 104','email'=>'contacto@valle-norte.demo','address'=>'Jr. Independencia 318, Trujillo','observations'=>'','active'=>true,'created_at'=>'2026-06-20 09:30:00','updated_at'=>'2026-06-20 09:30:00'],
        ['id'=>'company-005','name'=>'Servicios del Pacífico S.A.C.','ruc'=>'20400123455','phone'=>'044 610 105','email'=>'archivo@pacifico.demo','address'=>'Av. América Sur 765, Trujillo','observations'=>'Entidad demo inactiva conservada como antecedente.','active'=>false,'deactivation_reason'=>'Empresa demo sin operaciones actuales.','deactivated_at'=>'2026-06-25 15:00:00','created_at'=>'2026-06-20 09:40:00','updated_at'=>'2026-06-25 15:00:00'],
    ],
    'consortia' => [
        ['id'=>'consortium-001','name'=>'Consorcio Vías del Norte','mode'=>'ruc_propio','ruc'=>'20698765438','participants'=>[
            ['company_id'=>'company-001','active'=>true,'role_label'=>'Participante','is_tax_operator'=>false,'added_at'=>'2026-06-21 10:00:00','removed_at'=>'','removal_reason'=>''],
            ['company_id'=>'company-002','active'=>true,'role_label'=>'Participante','is_tax_operator'=>false,'added_at'=>'2026-06-21 10:00:00','removed_at'=>'','removal_reason'=>''],
        ],'observations'=>'Consorcio demo con RUC propio.','active'=>true,'created_at'=>'2026-06-21 10:00:00','updated_at'=>'2026-06-21 10:00:00'],
        ['id'=>'consortium-002','name'=>'Consorcio Vial Andino','mode'=>'operador_tributario','ruc'=>'','participants'=>[
            ['company_id'=>'company-003','active'=>true,'role_label'=>'Operador tributario','is_tax_operator'=>true,'added_at'=>'2026-06-22 11:00:00','removed_at'=>'','removal_reason'=>''],
            ['company_id'=>'company-004','active'=>true,'role_label'=>'Participante','is_tax_operator'=>false,'added_at'=>'2026-06-22 11:00:00','removed_at'=>'','removal_reason'=>''],
            ['company_id'=>'company-001','active'=>true,'role_label'=>'Participante','is_tax_operator'=>false,'added_at'=>'2026-06-22 11:00:00','removed_at'=>'','removal_reason'=>''],
        ],'observations'=>'Consorcio demo sin RUC propio.','active'=>true,'created_at'=>'2026-06-22 11:00:00','updated_at'=>'2026-06-22 11:00:00'],
    ],
    'contacts' => [
        ['id'=>'contact-001','full_name'=>'Carla Valladares','mobile'=>'949 510 201','email'=>'carla.valladares@constructoranorte.demo','document_type'=>'DNI','document'=>'45871236','label'=>'Coordinadora administrativa','observations'=>'','relationships'=>[['entity_id'=>'company-001','entity_type'=>'Empresa','label'=>'Contacto comercial','is_primary'=>true,'active'=>true],['entity_id'=>'consortium-001','entity_type'=>'Consorcio','label'=>'Coordinadora','is_primary'=>false,'active'=>true]],'active'=>true],
        ['id'=>'contact-002','full_name'=>'Renato Quispe','mobile'=>'949 510 202','email'=>'renato.quispe@ingenieriaandina.demo','document_type'=>'DNI','document'=>'47125896','label'=>'Representante de obra','observations'=>'','relationships'=>[['entity_id'=>'company-002','entity_type'=>'Empresa','label'=>'Contacto principal de obra','is_primary'=>true,'active'=>true],['entity_id'=>'consortium-001','entity_type'=>'Consorcio','label'=>'Representante de obra','is_primary'=>false,'active'=>true]],'active'=>true],
        ['id'=>'contact-003','full_name'=>'Mariela Castañeda','mobile'=>'949 510 203','email'=>'mariela.castaneda@consorciovias.demo','document_type'=>'DNI','document'=>'40981257','label'=>'Apoderada','observations'=>'','relationships'=>[['entity_id'=>'consortium-001','entity_type'=>'Consorcio','label'=>'Contacto principal','is_primary'=>true,'active'=>true]],'active'=>true],
        ['id'=>'contact-004','full_name'=>'Diego Fernández','mobile'=>'949 510 204','email'=>'','document_type'=>'','document'=>'','label'=>'Solicitante inicial','observations'=>'Contacto independiente sin entidad vinculada.','relationships'=>[],'active'=>true],
        ['id'=>'contact-005','full_name'=>'Lucía Paredes','mobile'=>'949 510 205','email'=>'lucia.paredes@valle-norte.demo','document_type'=>'DNI','document'=>'44317852','label'=>'Administradora','observations'=>'','relationships'=>[['entity_id'=>'company-004','entity_type'=>'Empresa','label'=>'Contacto principal','is_primary'=>true,'active'=>true],['entity_id'=>'consortium-002','entity_type'=>'Consorcio','label'=>'Administradora','is_primary'=>false,'active'=>true]],'active'=>true],
        ['id'=>'contact-006','full_name'=>'Miguel Salazar','mobile'=>'949 510 206','email'=>'miguel.salazar@transporteselsol.demo','document_type'=>'DNI','document'=>'46591238','label'=>'Jefe de operaciones','observations'=>'','relationships'=>[['entity_id'=>'company-003','entity_type'=>'Empresa','label'=>'Contacto principal','is_primary'=>true,'active'=>true],['entity_id'=>'consortium-002','entity_type'=>'Consorcio','label'=>'Contacto operativo','is_primary'=>false,'active'=>true]],'active'=>true],
        ['id'=>'contact-007','full_name'=>'Andrea Cueva','mobile'=>'949 510 207','email'=>'andrea.cueva@constructoranorte.demo','document_type'=>'DNI','document'=>'46872195','label'=>'Asistente de administración','observations'=>'','relationships'=>[['entity_id'=>'company-001','entity_type'=>'Empresa','label'=>'Contacto alterno','is_primary'=>false,'active'=>true]],'active'=>true],
        ['id'=>'contact-008','full_name'=>'Rubén Tello','mobile'=>'949 510 208','email'=>'ruben.tello@pacifico.demo','document_type'=>'DNI','document'=>'45562318','label'=>'Contacto histórico','observations'=>'Relacionado a una empresa inactiva.','relationships'=>[['entity_id'=>'company-005','entity_type'=>'Empresa','label'=>'Contacto principal histórico','is_primary'=>true,'active'=>true]],'active'=>true],
    ],
];
