<?php
declare(strict_types=1);
require __DIR__.'/../config/bootstrap.php';
$user=requireAuth(); header('Content-Type: application/json; charset=utf-8');
function reply(bool $ok,string $message,array $extra=[],int $status=200):never{http_response_code($status);echo json_encode(array_merge(['ok'=>$ok,'message'=>$message],$extra),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if((string)($user['role']??'')!=='gerente')reply(false,'Solo el gerente puede cargar logos en Catálogos.',[],403);if($_SERVER['REQUEST_METHOD']!=='POST')reply(false,'Método no permitido.',[],405);if(!isset($_FILES['logo'])||!is_array($_FILES['logo']))reply(false,'Selecciona una imagen.',[],422);
$f=$_FILES['logo'];if((int)($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)reply(false,'No se pudo recibir la imagen.',[],422);if((int)($f['size']??0)<=0||(int)$f['size']>5*1024*1024)reply(false,'El logo debe pesar como máximo 5 MB.',[],422);
$mime=(new finfo(FILEINFO_MIME_TYPE))->file((string)$f['tmp_name']);$map=['image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp'];if(!isset($map[$mime]))reply(false,'Formato no permitido. Usa PNG, JPG o WEBP.',[],422);
$code=trim((string)preg_replace('/[^a-z0-9_-]/i','-',(string)($_POST['insurer_code']??'aseguradora')),'-')?:'aseguradora';$d=new DateTimeImmutable('now',new DateTimeZone('America/Lima'));$rel='catalogos/aseguradoras/'.$d->format('Y/m/d');$base=realpath(__DIR__.'/../almacen');if($base===false)reply(false,'No existe almacenamiento.',[],500);$dir=$base.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$rel);if(!is_dir($dir)&&!mkdir($dir,0775,true)&&!is_dir($dir))reply(false,'No se pudo preparar la carpeta.',[],500);$name=$code.'-'.bin2hex(random_bytes(8)).'.'.$map[$mime];if(!move_uploaded_file((string)$f['tmp_name'],$dir.DIRECTORY_SEPARATOR.$name))reply(false,'No se pudo guardar el logo.',[],500);reply(true,'Logo cargado.',['file'=>['relative_path'=>$rel.'/'.$name,'original_name'=>(string)$f['name'],'mime'=>$mime,'size_bytes'=>(int)$f['size']]]);
